const data = {
  products: [
    {
      _id : '1',                 
      name: 'Magmus 3 Inch Brass Locking L Hinges Satin Silver Premium',
      size: '3 inch x 3/8 x 1.1/4 x 6 mm',
      DSIN: 'MAG-100471.05',
      image: '/images/p1.webp',
      price: 199,
      rating: 4.0,
      numReviews: 14,
      countInStock: 10,
      brand: 'Magmus',
      description: 'High quality product',
    },
    {
      _id : '2',
      name: 'Magmus 3 Inch Brass Locking L Hinges Satin Black Premium',
      size: '3 inch x 3/8 x 1.1/4 x 6 mm',
      DSIN: 'MAG-100471.08',
      image: '/images/p2.jpg',
      price: 253,
      rating: 4.5,
      numReviews: 15,
      countInStock: 10,
      brand: 'Magmus',
      description: 'High quality product',
    },
    {
      _id : '3',
      name: 'Magmus 3 Inch Brass Locking L Hinges Satin Silver Premium',
      size: '3 inch x 3/8 x 1.1/4 x 12 mm',
      DSIN: 'MAG-100472.05',
      image: '/images/p1.webp',
      price: 217,
      rating: 4.5,
      numReviews: 14,
      countInStock: 10,
      brand: 'Magmus',
      description: 'High quality product',
    },
    {
      _id : '4',
      name: 'Magmus Brass Folding Bracket Premium Satin Silver',
      size: '2" x 10 mm',
      DSIN: 'MAG-802010.05',
      image: '/images/p4.webp',
      price: 210,
      rating: 3.5,
      numReviews: 17,
      countInStock: 10,
      brand: 'Magmus',
      description: 'High quality product',
    },
    {
      _id : '5',
      name: 'Magmus Brass Folding Bracket Premium Satin Silver',
      size: '2" x 12 mm',
      DSIN: 'MAG-802012.05',
      image: '/images/p4.webp',
      price: 220,
      rating: 2.5,
      numReviews: 10,
      countInStock: 10,
      brand: 'Magmus',
      description: 'High quality product',
    },
    {
      _id : '6',
      name: 'Magmus Furniture Glide Plint Pin 22 mm',
      size: '22mm',
      DSIN: 'MAG-103796.07',
      image: '/images/p6.webp',
      price: 30,
      rating: 1.5,
      numReviews: 15,
      countInStock: 0,
      brand: 'Magmus',
      description: 'High quality product',
    },
    {
      _id : '7',
      name: 'Magmus 3" S.S. Butt Door Hinges - Welded Soft Movement Matt',
      size: '3" x 16',
      DSIN: 'MAG-100141.00',
      image: '/images/p7.webp',
      price: 51,
      rating: 3.5,
      numReviews: 12,
      countInStock: 0,
      brand: 'Magmus',
      description: 'High quality product',
    },
  ],
};

export default data;